---
- name: creating a user
  hosts: group2
  tasks:
    - name: create user
      user:
        name: "{{d}}"
        password: "{{e}}"
        uid: "{{f}}"
        comment: "{{g}}"
        home: "{{h}}"
        shell: "{{i}}"
    - name: copy files
      copy:
        src: "{{j}}"
        dest: "{{h}}"
...

