---
- name: activity1
  hosts: all
  tasks:
    - name: create a user
      user:
        name: "{{a}}"
        password: "{{b}}"
        uid: "{{c}}"
        home: "{{d}}"
    - name: create file in users home
      file:
        name: "{{e}}"
        state: "{{f}}"
...          

