---
- name: implementing loops
  hosts: group1
  tasks:
    - name: create user
      user:
        name: "{{item.a}}"
        password: "{{item.b}}"
        uid: "{{item.c}}"
        home: "{{item.d}}"
      with_items:
        - {a: adam,b: adam123,c: 2222,d: /home/adam}
        - {a: rock,b: rock123,c: 3333,d: /home/rock}
    - name: copy files
      copy:
         src: "{{item.a}}"
         dest: "{{item.b}}"
      with_items:
        - {a: /etc/passwd,b: /home/adam}
        - {a: /etc/passwd,b: /home/rock}
...          



